=== LordKBX/Remote_Commander/Server/Module.dtd
<!-- * = 0 or more -->
<!-- + = 1 or more -->
<!-- ? = optional -->
<!ELEMENT Module (Id, MinWidth, MinHeight, Template, Style, Vars, Declares, Scriptxs)>
<!ELEMENT Id (#PCDATA)>
<!ELEMENT MinWidth (#PCDATA)>
<!ELEMENT MinHeight (#PCDATA)>
<!ELEMENT Template (#PCDATA)>
<!ELEMENT Style (#PCDATA)>
<!ELEMENT Vars (Var*)>
<!ELEMENT Var (#PCDATA)>
<!ATTLIST Var name CDATA #REQUIRED>
<!ATTLIST Var eval CDATA #IMPLIED>
<!ELEMENT Declares (Declare*)>
<!ELEMENT Declare (#PCDATA)>
<!ELEMENT Scriptxs (Scriptx*)>
<!ELEMENT Scriptx (#PCDATA)>
<!ATTLIST Scriptx sources CDATA #REQUIRED>

=== LordKBX/Remote_Commander/Server/Mods/VolumeVertical.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Module SYSTEM "../Module.dtd">
<Module>
  <Id>VolumeVertical</Id>
  <MinWidth>1</MinWidth>
  <MinHeight>2</MinHeight>
  <!-- %bmid% = blockModuleId, %mid% = ModuleId -->
  <Template><![CDATA[<div class="blockVolVertical" id="%bmid%">
  <div class="top" onclick="var calc = app.modsVars['%mid%lastVol'] + 0.02; var obj={}; obj.function='Source'; obj.module='SoundInfo'; obj.method='SetVolume'; obj.data=calc; console.log(JSON.stringify(obj));  app.socketSend(JSON.stringify(obj));">
  </div>
  <div class="mid" muted="0" onclick="var obj={}; obj.function='Source'; obj.module='SoundInfo'; obj.method='SetMute'; obj.data=!app.modsVars['%mid%lastMute']; console.log(JSON.stringify(obj));  app.socketSend(JSON.stringify(obj));">
  00%</div>
  <div class="bot" onclick="var calc = app.modsVars['%mid%lastVol'] - 0.02; var obj={}; obj.function='Source'; obj.module='SoundInfo'; obj.method='SetVolume'; obj.data=calc; console.log(JSON.stringify(obj));  app.socketSend(JSON.stringify(obj));">
  </div>
</div>]]></Template>
  <Style><![CDATA[:root{
  --bh_%bmid%: %mh%px;
  --bw_%bmid%: %mw%px;
  --coef_%bmid%: 0.6;
  --coef2_%bmid%: 0.4;
}

.blockVolVertical[id="%bmid%"]{
  background: #666666;
  color: #ffffff;
  width: var(--bw_%bmid%);
  height: var(--bh_%bmid%);
}
.blockVolVertical[id="%bmid%"] .top{
  margin: 0 auto;
  display: block;
  background: url('%iconVolUp%'); background-size:100%;
  width: calc(var(--bw_%bmid%) * var(--coef_%bmid%));
  height: calc(var(--bw_%bmid%) * var(--coef_%bmid%));
  position: relative;
  top: 5px;
}
.blockVolVertical[id="%bmid%"] .mid{
  margin: 0 auto;
  display: block;
  width: calc(var(--bw_%bmid%) * var(--coef_%bmid%));
  height: calc(var(--bw_%bmid%) * var(--coef_%bmid%));
  line-height: calc(var(--bw_%bmid%) * var(--coef_%bmid%));
  font-size: calc(calc(var(--bw_%bmid%) * var(--coef_%bmid%)) * var(--coef2_%bmid%));
  text-align: center;
  position: relative;
  top: calc(50% - calc(calc(var(--bw_%bmid%) * var(--coef_%bmid%)) * 1.5));
}
.blockVolVertical[id="%bmid%"] .mid[muted="1"]{
  background:#ff8888;
}
.blockVolVertical[id="%bmid%"] .mid[muted="0"]{
  background:#88ff88;
}
.blockVolVertical[id="%bmid%"] .bot{
  margin: 0 auto;
  display: block;
  background: url('%iconVolDown%'); background-size:100%;
  width: calc(var(--bw_%bmid%) * var(--coef_%bmid%));
  height: calc(var(--bw_%bmid%) * var(--coef_%bmid%));
  position: relative;
  top: calc(100% - calc(calc(var(--bw_%bmid%) * var(--coef_%bmid%)) * 3.1)); 
}]]></Style>
  <Vars>
    <Var name="mw" eval="true"><![CDATA[ModWidth]]></Var>
    <Var name="mh" eval="true"><![CDATA[ModHeight]]></Var>
    <Var name="iconVolUp"><![CDATA[data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAAHdbkFIAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADdYAAA3WAZBveZwAAAmfSURBVGhD3Ztb6G1FHcf3MYUT5DHIUk4KFkYlGIZdDHqoR+0pjga+lBaoPWVlUNFDccBuSj3ZBcpe4jxo9GZPYXgExZCiILPQf5KGdgEzQSHr3/cza76r35o9sy77v44d+sJnz2XNXnvWrLn+ZvZmf38/clS8FOPixRuCH57DrV1EvZ8PbusLFwhf/CLuIX28tNlszhSldP/N9STogl3EX8VrUyjLCZ4TR/BIRBzqvJv98g6+gLowCQIPi7tjnO9QfhuluDP08QweYqQTIn1DIu4It7lfWITtJn/8CcS37EcnSUBBvaIL9wn8k/vk4UZBhCOj+sf8d3Yjt+KWkfCMQGQ+5VFcKKgn6GOiT997BPIXSlAM3yFSrqYK2i+/dh2lQnhY4KJ0t+zyhUHNyXIa9CJf3BMXpOByHW49I5wQqHU9xQ8CEoUT4+K1Mtx8jecI6wVxX+ftNUg/CBQcF8+LJ8WxHLeFS9+i5ClleFC8SlDAl+U4GCrc7YcCxbgS6g06S6Q4X7hGIIcjlEMZh5J/rCYiZ7l1LXUJj4h3ERPkZ659MSo1VxSzZsU4++G64E9todQbxA86b1UfyW5S7QYt8UjwvuwmLbkB5QE/y25Seq+4XfC/d5ZiXP+FoHPFfRTEJ8WgO8+gr2S3vObrun0IVKASoTL+YoH6GwCKYXNZET5DoBSOF1zPLxcxPnJSoD4uvgUX1k+zHx4Sj4Uw14YFGu82whHxiFiim0XtXgPG6tE1wjl/VnxYkPu5vFfE79dVyZX7JfRKUUtTg0GgFg93CSv1QCYmciVAc3+YGhZVSxP5hUD3ihTnC7xjVJtE1HD7QEz+rFraEmo5elYMOmTEu7Ouy651pfhQ5918VXy28ybVvj8mplTfFreTI0Y/9AERc2rR/97SeffvFDFNmbZ1rS/yQBIehl5UTSDhv6jzzs7AXgDxyhy+WpDmIZEGlHYT2V0MSgYxRXD4biKk1/BBBj6BRzqe3VK8373Ou7kwu2vojXyMVcKaXhCHO2/KzJOdd3ElfEBckcjvA6xBR9Egtv+/ZBfV0pZ4QEnrtfIibRPRc5XXWngajGrXjYdBRKVO8WUiYNpn0XPV0izBgzf6sRhcrw1G/xS8S6CF8H4NHciUmKvwjv2d3wtqP/f7oBiqzNEI1I3bxJR+I94tavfYwq1giY6JawW1+HzxonhU3CO+Jf4k5qvMUQNmfkvE5IUBrnavAdXIAKviKFbLjB2snGM6SpKxJJoGEKvu0WZdjcy4SaLavHeMdwqGdov1Uy1dNQOxGWIemtMxtcCiZDHT2kpTRvBj1pLO6GzRGimZXVlbmRgEhIuttV6vcZNArQxAfLDB64iJmDSgJb3f74Q1lgGIJdG/VveE5wjWfejt2R3T2ULZ37wpheaJkdQ96dPZ7TPwRHbfkd0x3SQwFaL7hScdc/RdQcZfJzpTYy4OKxZZjVjkVwripqZrJTRRRGeVSuDrKSfdk1msapgVR1zkuGeJn4hd9PPsviV9dplJirnkaWpiMhHTwVgJMOlIE48C95hHCVgxgTPAdJxpuRXTmLEMWGU83TY67krIiFYTM9gxk8uuYuREVzkDv87uGqJO7WUshx1HPUJvniqBXcSM6KKM5XCMQ4edgddndw1dLzylsxyOcehpZyAtEl5GeYHzoDPQEu/M7wvVtlt20Q3ZPUEGMHci3t2UmDGzTJ+rWrGjz2X3R7RJZrDoAVG214iHXRQ7pKVdMVipJxxETMDEw2LucKZYmgGmdyhZ0VwHvpTdk9lt6R+CImWxgbvLK2Faj76ZPslFxmIpFeNbxFeC5pQAc0zU70HFiy5KxEIyXmsRX8lUBmyqS8YpE5vhH8SXO+/mX2KqiaL4SsZ0h7i6825end1OMTcZVrDW3NcBl1TiwLZB1G+4mEEgwM6UVZsDzMH2QESLOSS20m1FBGKdQPQT54pa2siNIqpmouupRhYwo6npMcHWHOa2aDm1qGyTC9RqZAN6TNb+U8KGUC3uGinhyqJVsJWGuf8q8VZxEDFWMYO6S7ABsmqG1ygA1hefEjcLFlhTYvKFEeVv2Y8wPWI4PZr9U/q7oCf/RvbvrlgdFkAD9VK2JhosjXFOo52Ce3Av7tkSeSFPte+PUo1sQG2he4x2F4uucmyzb234Ldt7o8gbeZzdB1QjCxg84uBkMcAsGaiW0BrUapCHONhZ5Hlr4CupRgbigGhhOpo7V1kC1n+bHpbMbQ15Im+l0nGTFtVIQXuKJkrEZGrtB2cyF3carF0KwJDHuEeLeJZqH7EVIUrDMFPYtas6U+na5ME6SAEY8uzptzU4CgaDgChnPXQ0szuUCWIVj2Kz6+Odt9caBQDkvewsB7aqmJglWtRSy3yNVhWnt+ZkC0tK0pXz3rUKwHgZarHvkq45gRfm1tQCfYpWFedtxCOm5lQXAJTziLSd5otxjs1mUGsCQ8aWiipuY3KLl6MAeCYfC0U8c1r1YiSI83VWxZzkPKg4qIQhm0Oduxqzp6RX2HMvESPimbziRzzzMQqAjc8o9hHmytvAUO5V/FFwJvh0Uvls11IA7Ppajwsy/v8qno1ntK6gANjytp7K7ummO0Ws7ibKxztLyhNY8RnPpwDi3sCcpej/QrRfrHYlUTxHLc3zIio+YzpUzmEH61JBez7d9BlBH1MSFQ9nRXxQC/FsPKP1KAXg/SpE6WDFmStsnd7GtN3zdBbPFmvAPYyP/A8mii3Mcgw1S+cBrYlPya7zAG/DQjxk3qI80HLUJrHbxKfxZLFp/Z3OOxAb2Bd33qbiMU+LH/ma+IKoDY3sHe513iR2ZtnqW1M+MmrdLm5xyVAQ5SFptvRj6S1lbPFTzgxP9UzQxxMsnrV7+XxksGFHGwALlrXMXFNrg1NZADxDNOMN7PVlYi7471VW+S+7g9BaHZZaqwDikS3Es/G/oz5NTGyoGqXFF5vbkhP1c2g1EXTQAiCvpZ2QZ0rVPjIIFHC0q7QAY3PbuskKlE1k1wIgb6VdkGdYdGowwg3j/yosbG5r1whwE1laAOSltAMi8j76wqqRFTAv1woCmxvt7FTUiin4TX67tPsh8jppEodq5ARUp9JijKhqmJ4OOnyOwb35jbJpIvLUrOot0pvbUcyrPypuFZxBrImjBszRMVbg/krwt4PWj3JP/ov5NsEy/f3Z9f+MS/1ZfF58X+z0IAcpgFJsklIgzLi644jr67cCo8b3hA+OHkhrFkBL7Pi+R/BvU8xQrNDOExwW8cKEpSx/VuCP63uCLfFfCv6IsOw4/iJtNv8BQoHLoGP7h7QAAAAASUVORK5CYII=]]></Var>
    <Var name="iconVolDown"><![CDATA[data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAAHdbkFIAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAAboAAAG6AeirAQYAAAkOSURBVGhD3ZtJqB1FFIZvNEokxJVjjBhRQdyYgFGQqOAQEQy4EI26cCa6EMUBXAgm4CKKOKxcaCBiwI0LMYJgMAujCzVOO3GKgolDXEhEImp8/l91nfZ03aq+3ff2i8EfvtfVVXW7T1XXXPVGc3NznsViv/fzgfc7NxzgmgtEtZs/PNYClgkLDCzQn/2j0ehYkUrPH20kQnVbefwsjg93URbhgDgGh4THgso5mkufYAGouieCY6t4wvvZE9Jfo+B3hP58hAMf6WURfiHhF17xjTBxb9fg9q9A/Mrc6EMieA+LYK+cw4YrRfW+cdXJDF/OwZPX4faexkcCYfxJAr+VeEStEXX82iGQv/cgf0+GB6smZbR9/Fw4CpmwVZwcbquIduUHjZKTEw/YK+wB/RXThHwa4WWBSuHVN3YgMsf7+bD0vvgZw5OddsWrqRG/cZNwn/hM7BBro98YZGIqvgB8Jc4Wl4vLoh805Z62USDvl3K0QKH8gAWsEsjuPWk9ABTcbSURmcmlsNAk7BSX4OO0QpQe2lBVGP6NaG9E3q/0oAO5r3C6eLFyTtSi3ANKwhJPUJ8HkAxPJfKAbIh4eT9ze1aIbTjuFu9FTw/aFK9pmIUHC+qbDBQilPpfIFD9AED+3sBUf79IoHDvAwBdL1J/4yuBaj8faHwtTHvEX5Uz6EbRiN+4aYFauFN01UHBx8k9q0HWM2I13HSxyMUrQckw7RW5OFkDrF1CS0UuTg46gZw/vC9MjbDGjTB1fTElzCsXx0NOoO0i+FmAtbTI/Nqw+oEY/JlycVMo5YjC2miQkW/2bolX01Xiuso5elw8XDmDcr9v0wbxqLgDi+j9UNrzmW4RD1bOuS3Cx0nj5sJKBOGg60XZCBLu5ZWzswEM7UqQYOLQRgQH/T46QtgDwIS7rwFdCA0U/cnTfBTpqXhNxffdXTlHy+J1CB3JHyuEBwXGTCpEzEkWVc7RqeK7ytm7EH4izhUn+CwxUSW9fw5f//fFK8rFTbEOJfQLaaA1FLRcaVgJGwajXLhh3SA6RQT/NBKEoVJUsQ3vgXXe6CXRCG/cZKDJ9NogcvE8fJ5PhFed4pSsZwu3Cd8M5/SaOF7kfj+G1YI+WisuEudFmGPtijwvfhPdlVpUgMEFg4yuelt0qU0TDWBWnOoZwczZt5zMqOlLaGq9mHX7542R9YxYlUS5cW8bjJ68GF3l4mUN8NWQAtcpKwuwomRipDUWZ8xDmPo0RktEqaNidGUaM6JxI6yKlebrOe4SqGSAYWp8Dh/BGp0+rd/nwjTJAJ8Ttb9N7+jFmM6jpfHapiVC5o/OCnfdRHvxQOUMK21BZgBrCmhdvLZpvWDBEb0jmBF3lY05VoqjgytmhanOmgI+y68S+E0aLaVYFWWmFQy4Pdw2O5rVgsGox/S3WCgsbl8DwBQMyM2BeVhOweqEaQywFnMxZcCGWDk9JG6tnEF0QkPonni90wphSa+ILZVzUH0Qr+eZAVSRofSk+KYF9EO81gZ8H69D6DhxWgteS80A1taGEnNKGrYSyN67yxxhknAIxZwA1QaUxIyIJte0MF5n1c3xuhMDXq/cnT7Dn4Jp+qy6N17DSh8jWMRQOm0wPOuFyTdI07aEjDHH+oIwSm6BgYfJmuS+BtjiVVhFszJwU7x+Ga8l/SooyV/Ea99PQg94fuUcPRf+YkXExFTK+5fwnwR1yQHrd+o9KB/I9MnERNKHlfCfZJIBtlTXGHH5arhH3FA5G+sAbfKfpE1sca2qnMmIy1sTYQZr6vo54JyMH/j5xVghb9w42JkysaAwqXbksPVAxLfPxSkaAL5MINqJdO09ByMrr3pVNEfWM4GllJxY5WJrLiy3ZcRK6MScy3oWoMVk7t8mspo1hNzvswQL50Fs3rKOcI24QnSpUTn9LraLV8U2sU8MqiEygGaA5uMx0XWOwrLkj8IGYmxinyi6Dkt2i0eEP74wnXxx6AEVNF0/86LCUhm7VNpJ8Ayela67eWFLcR2ujaxnCzSP1p150VTS7E3TXPaFd/AuW+/1wrZwuKArWc8EXug7JxMdTJ+Oqg+lTi0HNvjOzoTNEz9I1tPhO0QTS0ddxyp9oKjb0kOfsa2BTdiWqrVEZD0F9SnNVQZTQyecwZzfaTBNkwEGNvo9WkRasm3EmIdIF4apV0MXdYbSubbENEsGGNicvqNxFAwaNyId9dDQzLJG7PFF3IvNLmZHXkNkAGB72lg2Dk/4yKkRTN1mbdVLRZzpJCdbbJXPppWmoTIASIM/Q4HqQx0WiWGm34iZNEGfRKmIM5kfO2Iq5jMDDD+OIK1hO80Ctwmv0gAGw/qKIm6LySUORQaQJi/SHGbEjNmvDsPCSs8KdrRn1VviKMG84A08/mORJtJmIs1ryYB0zbnrCTzE2J+5AKTzAI4T/FU5DxulabuIDGDH18Qk5dPK+b8UaSONprA87jOAYvJ35TysxCaFWqyp4JSUibT56h0ywG9OTH+2en7F6fJvp+QX4eXTuJfWMR0/22H6HGkvQOttYbO05IeiFwDS5rWVEsBJDy9bv+yiawUbMoD7cFeatl3kCv8H4wctbGGmOWf0HQeUBj4ph6oE+AMtpHlxGOpKt4sXcERtFL7xMK0WZ1bOovwxTxMveUKwjJXrGpeL3ZUziO4qPT46q+zIqOkOsdnnDl/Lq++Z5ZS2yU86MpzvEpCeIKr313wkZk7+CDpqO9Peh0lzg/nMAL9DgUhjPcNNI1Ml7N+rTOl/2c1CaXaYaqgM8Ee2EGlrzHB9ZE+64suKSp8T9V0oVRE0awZga7qild0iGvNwcLQrLbZ9jpL1gWNn/l2zZEA6ruG5vU4Npvj/qzCx5jZ0iQCrIn0zAFvSdUCUPanoyXpmoN7kMoLcpZ4NtWzWB97Ju3ONK7Y26nqJrOcEKE65dXjE0tOs3WcbPDtd3jJhU7Golwi5NIPWiE2CM4glMSFhc5MFEtYI2A/8SaSzToblJwgmK/yvBP+PyeZqesDK62PB/9O8Ge6m0KwZ4MURFEaUN4oLBQkaUmTYu4IN0c3iDzGzhsyAkhaLS8UZggMiKYgpeQonaXeIfsfxe2k0+gfhOuACBbISdAAAAABJRU5ErkJggg==]]></Var>
